version: '3'

services:

  db:
    image: 'postgres:14-alpine'
    network_mode: bridge
    container_name: db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: 'docker-spring-boot-postgres:latest'
    network_mode: bridge
    build:
      context: .
    container_name: app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create